[system]
k_max = 3
n_particles = 10
hbar2_over_2m = 1.0
c0 = 0.0
c1 = 0.2
target_Mz = 0

[training]
n_walkers = 1000
n_thermal = 500
n_steps = 100
n_interval = 4
n_epochs = 1000

[model]
hidden_dim = 64

[io]
log_iter = 10
save_iter = 100